"""Change content to be nullable false

Revision ID: 038ebd578ac3
Revises: 7dce07035c54
Create Date: 2025-10-21 12:49:25.403507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038ebd578ac3'
down_revision = '7dce07035c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
